org: jpbogle
app: cardinal
service: cardinal-generators
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  http:
    cors: true
  apiGateway:
    binaryMediaTypes:
      - "*/*"

package:
  individually: true
  include:
    - ./idls/**
    - ./img-generator/fonts/**
    - ./img-generator/assets/**
  exclude:
    - "./node_modules"
    - "./package-lock.json"
    - "./yarn.lock"

functions:
  img-generator:
    environment:
      FONTCONFIG_FILE: /var/task/fonts/fonts.conf
    handler: img-generator/handler.generate
    timeout: 10
    events:
      - http:
          path: /img/{mintId}
          method: get
          contentHandling: CONVERT_TO_BINARY
  metadata-generator:
    handler: metadata-generator/handler.generate
    timeout: 10
    events:
      - http:
          path: /metadata/{mintId}
          method: get

custom:
  apigwBinary:
    types:
      - "image/png"
  domains:
    main:
      domainName: nft.cardinal.so
    dev:
      domainName: dev-nft.cardinal.so
  customDomain:
    domainName: ${self:custom.domains.${opt:stage}.domainName}
    certificateName: "*.cardinal.so"
    createRoute53Record: true
    autoDomain: true

plugins:
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies
